#!/usr/bin/env bash

set -e

cat << EOS
Usage: artenv <command> <arg>

Environment commands:
  register          Register an analysis environment
  remove            Remove a registered environment
  archive           Archive an environment (hide from \`ls', still usable)
  unarchive         Unarchive an environment
  ls                Print the environment list
  info              Print detail information of the environment
  new               Create the new working directory from templates
  shell             Set or show the activated environment in the current shell
  default           Set or show the default environment

Version commands:
  version <cmd>     Manage artemis versions
                    (ls/register/remove/archive/unarchive/install/current;
                     see \`artenv version help')

Template commands:
  templates <cmd>   Manage project templates from external git repos
                    (ls/repos/update; see \`artenv templates help')

Utility commands:
  init              Configure the shell environment for artenv
  doctor            Diagnose a registered environment
  migrate           Migrate v1 (symlink) data to v2 (TOML)
  upgrade           Update artenv to the latest release
  commands          List all available commands
  --version         Show the version of artenv

Deprecated aliases (kept for compatibility):
  versions          -> version ls
  register-version  -> version register
  remove-version    -> version remove
  archive-version   -> version archive
  unarchive-version -> version unarchive
  install           -> version install
  register-env      -> register
  remove-env        -> remove
  archive-env       -> archive
  unarchive-env     -> unarchive
EOS
