#!/usr/bin/env bash

set -e

if [ $# != 1 ]; then
    echo "artenv default <env-name>"
    exit 1
fi

env=$1
env_dir="${ARTENV_ROOT}/envs/${env}"

if [ ! -d "$env_dir" ]; then
    echo "${env} not found"
    exit 1
fi

target="${ARTENV_ROOT}/env"

if [ -L $target ]; then
    unlink $target
fi

ln -s $env_dir $target
