#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${script_dir}/util.sh"

main() {
  [[ -n "${ARTENV_ROOT:-}" ]] || die "ARTENV_ROOT is not set"
  [[ $# -eq 1 ]] || die "usage: artenv register-version <version>"

  local version="$1"
  local version_dir="${ARTENV_ROOT}/versions/${version}"
  local tmp_dir

  local artsys=""
  local rootsys=""
  local yamlcpp=""
  local yamllib=""
  local yamlcmake=""

  [[ ! -e "${version_dir}" ]] || die "${version} already exists"

  read -e -r -p "Enter the path to artemis> " artsys
  require_dir "${artsys}"
  artsys="$(resolve_path "${artsys}")"
  require_dir "${artsys}/bin"
  require_dir "${artsys}/lib"

  read -e -r -p "Enter the path to root> " rootsys
  require_dir "${rootsys}"
  rootsys="$(resolve_path "${rootsys}")"
  require_dir "${rootsys}/bin"
  require_dir "${rootsys}/lib"
  require_file "${rootsys}/bin/root-config"

  read -e -r -p "Enter the path to yaml-cpp> " yamlcpp
  require_dir "${yamlcpp}"
  yamlcpp="$(resolve_path "${yamlcpp}")"

  if [[ -d "${yamlcpp}/lib" ]]; then
    yamllib="$(resolve_path "${yamlcpp}/lib")"
  elif [[ -d "${yamlcpp}/lib64" ]]; then
    yamllib="$(resolve_path "${yamlcpp}/lib64")"
  else
    die "Could not find yaml-cpp library in ${yamlcpp}"
  fi

  if [[ -d "${yamllib}/cmake/yaml-cpp" ]]; then
    yamlcmake="$(resolve_path "${yamllib}/cmake")"
  elif [[ -d "${yamlcpp}/share/cmake/yaml-cpp" ]]; then
    yamlcmake="$(resolve_path "${yamlcpp}/share/cmake")"
  else
    die "Could not find yaml-cpp CMake config in ${yamlcpp}"
  fi

  ensure_dir "${ARTENV_ROOT}/versions"
  tmp_dir="$(mktemp -d "${ARTENV_ROOT}/versions/.tmp.${version}.XXXXXX")"
  trap 'rm -rf -- "${tmp_dir}"' EXIT

  ln -s -- "${artsys}"    "${tmp_dir}/artsys"
  ln -s -- "${rootsys}"   "${tmp_dir}/rootsys"
  ln -s -- "${yamllib}"   "${tmp_dir}/yamllib"
  ln -s -- "${yamlcmake}" "${tmp_dir}/yamlcmake"

  mv -- "${tmp_dir}" "${version_dir}"
  trap - EXIT

  printf '%s was registered\n' "${version}"
}

main "$@"
