#!/usr/bin/env bash

set -euo pipefail

function main() {
    if [[ -z "${ARTENV_ROOT:-}" ]]; then
        # shellcheck disable=SC2016
        echo 'export ARTENV_ROOT="$HOME/.artenv"'
    fi

    : "${ARTENV_ROOT:=${HOME}/.artenv}"

    [[ -d "${ARTENV_ROOT}/versions" ]] || mkdir -p -- "${ARTENV_ROOT}/versions"
    [[ -d "${ARTENV_ROOT}/envs"     ]] || mkdir -p -- "${ARTENV_ROOT}/envs"

    if [[ -L "${ARTENV_ROOT}/env" || -e "${ARTENV_ROOT}/env" ]]; then
        env=$(readlink "${ARTENV_ROOT}/env")
        env=$(basename "${env}")
        source artenv-sh-shell "${env}"
    fi

    cat << 'EOS'
artenv() {
    local commmand
    command="${1:-}"
    if [ "$#" -gt 0 ]
    then
        shift
    fi
    case "$command" in
        (shell) eval "$(artenv "sh-$command" "$@")" ;;
        (*) command artenv "$command" "$@" ;;
    esac
}
EOS
    exit 0
}

main
