#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${script_dir}/util.sh"

print_var() {
  local name="$1"
  local value="$2"
  printf '  %-22s %s\n' "${name}" "${value}"
}

confirm_yes() {
  local prompt="$1"
  local ans=""

  read -r -p "${prompt}" ans
  case "${ans}" in
    y|Y|yes|YES)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

main() {
  local currentdir
  currentdir="$(pwd)"

  local rootsys=""
  local yamlcpp=""
  local yamllib=""
  local yamlcmake=""
  local artsrc=""
  local artbld=""
  local artsys=""

  local path="${PATH:-}"
  local libpath="${LIBPATH:-}"
  local shlib="${SHLIB_PATH:-}"
  local ldlib="${LD_LIBRARY_PATH:-}"
  local dyldlib="${DYLD_LIBRARY_PATH:-}"
  local cmake_prefix_path="${CMAKE_PREFIX_PATH:-}"

  local version=""
  local version_dir=""

  read -e -r -p "Enter the path to root> " rootsys
  require_dir "${rootsys}"
  rootsys="$(resolve_path "${rootsys}")"
  require_dir "${rootsys}/bin"
  require_dir "${rootsys}/lib"
  require_file "${rootsys}/bin/root-config"

  read -e -r -p "Enter the path to yaml-cpp> " yamlcpp
  require_dir "${yamlcpp}"
  yamlcpp="$(resolve_path "${yamlcpp}")"

  if [[ -d "${yamlcpp}/lib" ]]; then
    yamllib="$(resolve_path "${yamlcpp}/lib")"
  elif [[ -d "${yamlcpp}/lib64" ]]; then
    yamllib="$(resolve_path "${yamlcpp}/lib64")"
  else
    die "Could not find yaml-cpp library in ${yamlcpp}"
  fi

  if [[ -d "${yamllib}/cmake/yaml-cpp" ]]; then
    yamlcmake="$(resolve_path "${yamllib}/cmake")"
  elif [[ -d "${yamlcpp}/share/cmake/yaml-cpp" ]]; then
    yamlcmake="$(resolve_path "${yamlcpp}/share/cmake")"
  else
    die "Could not find yaml-cpp CMake config in ${yamlcpp}"
  fi

  read -e -r -p "Enter the path to the source of artemis> " artsrc
  require_dir "${artsrc}"
  artsrc="$(resolve_path "${artsrc}")"

  read -e -r -p "Enter the path to build directory> " artbld
  [[ -n "${artbld}" ]] || die "build directory is empty"
  artbld="$(resolve_path "${artbld}")"

  read -e -r -p "Enter the install prefix> " artsys
  [[ -n "${artsys}" ]] || die "install prefix is empty"
  if [[ -e "${artsys}" ]]; then
    artsys="$(resolve_path "${artsys}")"
  else
    mkdir -p -- "${artsys}"
    artsys="$(resolve_path "${artsys}")"
  fi

  printf '%s\n' "Configuration:"
  print_var "ROOTSYS" "${rootsys}"
  print_var "YAML_CPP_LIB" "${yamllib}"
  print_var "YAML_CPP_CMAKE" "${yamlcmake}"
  print_var "ARTEMIS_SOURCE" "${artsrc}"
  print_var "BUILD_DIR" "${artbld}"
  print_var "INSTALL_PREFIX" "${artsys}"

  if ! confirm_yes "OK? (y/N)> "; then
    exit 0
  fi

  if [[ -d "${artbld}" ]]; then
    if [[ -n "$(find "${artbld}" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]]; then
      if confirm_yes "Build directory is not empty. Is it OK to erase the directory? (y/N)> "; then
        [[ -n "${artbld}" ]] || die "build directory is empty"
        [[ "${artbld}" != "/" ]] || die "refusing to erase /"
        find "${artbld}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
      else
        exit 1
      fi
    fi
  else
    mkdir -p -- "${artbld}"
  fi

  if [[ -n "${ROOTSYS:-}" ]]; then
    path="$(remove_path "${path}" "${ROOTSYS}/bin")"
    libpath="$(remove_path "${libpath}" "${ROOTSYS}/lib")"
    shlib="$(remove_path "${shlib}" "${ROOTSYS}/lib")"
    ldlib="$(remove_path "${ldlib}" "${ROOTSYS}/lib")"
    dyldlib="$(remove_path "${dyldlib}" "${ROOTSYS}/lib")"
    cmake_prefix_path="$(remove_path "${cmake_prefix_path}" "${ROOTSYS}")"
  fi

  if [[ -n "${TARTSYS:-}" ]]; then
    path="$(remove_path "${path}" "${TARTSYS}/bin")"
    ldlib="$(remove_path "${ldlib}" "${TARTSYS}/lib")"
    cmake_prefix_path="$(remove_path "${cmake_prefix_path}" "${TARTSYS}")"
  fi

  if [[ -n "${YAML_CPP_LIB:-}" ]]; then
    ldlib="$(remove_path "${ldlib}" "${YAML_CPP_LIB}")"
  fi

  if [[ -n "${YAML_CPP_CMAKE:-}" ]]; then
    cmake_prefix_path="$(remove_path "${cmake_prefix_path}" "${YAML_CPP_CMAKE}")"
  fi

  path="$(prepend_path "${path}" "${rootsys}/bin")"
  ldlib="$(prepend_path "${ldlib}" "${yamllib}")"
  ldlib="$(prepend_path "${ldlib}" "${rootsys}/lib")"
  cmake_prefix_path="$(prepend_path "${cmake_prefix_path}" "${rootsys}")"
  cmake_prefix_path="$(prepend_path "${cmake_prefix_path}" "${yamlcmake}")"

  export PATH="${path}"
  export LIBPATH="${libpath}"
  export SHLIB_PATH="${shlib}"
  export LD_LIBRARY_PATH="${ldlib}"
  export DYLD_LIBRARY_PATH="${dyldlib}"
  export CMAKE_PREFIX_PATH="${cmake_prefix_path}"

  cd "${artbld}" || exit 1
  cmake "${artsrc}" -DCMAKE_INSTALL_PREFIX="${artsys}"
  make -j"$(getconf _NPROCESSORS_ONLN)"
  make install
  cd "${currentdir}" || exit 1

  if confirm_yes "Will you register this version to artenv? (y/N)> "; then
    [[ -n "${ARTENV_ROOT:-}" ]] || die "ARTENV_ROOT is not set"

    read -r -p "Enter the version name> " version
    [[ -n "${version}" ]] || die "version name is empty"
    [[ "${version}" != */* ]] || die "version name must not contain /"
    [[ "${version}" != "." && "${version}" != ".." ]] || die "invalid version name"

    version_dir="${ARTENV_ROOT}/versions/${version}"
    [[ ! -e "${version_dir}" ]] || die "${version} already exists"

    ensure_dir "${ARTENV_ROOT}/versions"
    mkdir -p -- "${version_dir}"
    ln -s -- "${artsys}" "${version_dir}/artsys"
    ln -s -- "${rootsys}" "${version_dir}/rootsys"
    ln -s -- "${yamllib}" "${version_dir}/yamllib"
    ln -s -- "${yamlcmake}" "${version_dir}/yamlcmake"

    printf '%s was registered\n' "${version}"
  fi
}

main "$@"
