#!/usr/bin/env bash
# Use git hash as version

set -euo pipefail

if [[ -n "${ARTENV_ROOT}" ]]; then
    cd "${ARTENV_ROOT}" || exit 1
    git_rev=$(git rev-parse HEAD)
    echo "artenv: ${git_rev}"
else
    echo "ARTENV_ROOT is not set"
fi
